version: '3'

volumes:
  dbdata:
  downloads:

services:
    loader:
      build:
        context: ./
        dockerfile: Dockerfile
      image: aolieman/dbp-same-thing-service:latest
      volumes:
        - dbdata:/dbdata
        - downloads:/downloads
      command: ["python" , "-m", "same_thing.loader"]
      tty: true

    http:
      build:
        context: ./
        dockerfile: Dockerfile
      image: aolieman/dbp-same-thing-service:latest
      ports:
        - "127.0.0.1:8027:8000"
      volumes:
        - dbdata:/dbdata
      command: ["gunicorn" , "-c", "python:gunicorn_config", "same_thing.app:app"]
