version: '3'

services:
    loader:
      image: dbp-same-thing:develop
      volumes:
        - ./same_thing:/usr/src/app/same_thing:ro

    http:
      image: dbp-same-thing:develop
      volumes:
        - ./same_thing:/usr/src/app/same_thing:ro
      command: ["uvicorn", "--host", "0.0.0.0", "--debug", "same_thing.app:app"]
