version: '3'

volumes:
  dbdata:
  downloads:

services:
    loader:
      build:
        context: ./
        dockerfile: Dockerfile
      image: dbp-same-thing:latest
#      environment:
#        -
      volumes:
        - ./same_thing:/usr/src/app/same_thing:ro
        - dbdata:/dbdata
        - downloads:/downloads
      command: ["python" , "-m", "same_thing.loader"]

    http:
      image: dbp-same-thing:latest
      ports:
        - "5000:5000"
#      environment:
#        -
      volumes:
        - ./same_thing:/usr/src/app/same_thing:ro
        - dbdata:/dbdata
        - downloads:/downloads
      command: ["python" , "-m", "same_thing.app"]
